/*
 * Lee Li The Multiple Choice Quiz program from 10/25/2018
 */

/**
 *
 * @author The G AppareL Darius
 */
public class TheMultipleChoiceQuiz extends javax.swing.JFrame {

    int CorrectMarks = 0;
    int Incorrect = 0;
    int Correct = 0;
    int A;
    int B;
    int C;
    int userAnswer;
    String False;
    String True;
    int totalCorrect;
    int totalIncorrect;
    
    
    public TheMultipleChoiceQuiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        lblHeader = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        txtQuestion1 = new javax.swing.JTextField();
        lblQuestion2 = new javax.swing.JLabel();
        txtQuestion2 = new javax.swing.JTextField();
        lblQuestion3 = new javax.swing.JLabel();
        txtQuestion3 = new javax.swing.JTextField();
        lblQuestion4 = new javax.swing.JLabel();
        txtQuestion4 = new javax.swing.JTextField();
        lblQuestion5 = new javax.swing.JLabel();
        txtQuestion5 = new javax.swing.JTextField();
        lblMarks = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        lblAnswer1 = new javax.swing.JLabel();
        lblAnswer2 = new javax.swing.JLabel();
        lblAnswer3 = new javax.swing.JLabel();
        lblAnswer4 = new javax.swing.JLabel();
        lblAnswer5 = new javax.swing.JLabel();
        lblRed = new javax.swing.JLabel();
        lblYellow = new javax.swing.JLabel();
        lblBlue = new javax.swing.JLabel();
        lbl232 = new javax.swing.JLabel();
        lbl246 = new javax.swing.JLabel();
        lbl3333 = new javax.swing.JLabel();
        lblChina = new javax.swing.JLabel();
        lblRussia = new javax.swing.JLabel();
        lblCanada = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        lblYes = new javax.swing.JLabel();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 0, 51));
        lblHeader.setText("The Multiple Choice Quiz");

        lblQuestion1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuestion1.setForeground(new java.awt.Color(255, 51, 153));
        lblQuestion1.setText("1. What color is banana ? ");

        txtQuestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestion1ActionPerformed(evt);
            }
        });

        lblQuestion2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuestion2.setForeground(new java.awt.Color(255, 0, 204));
        lblQuestion2.setText("2. What answer is 123+123 ?");

        txtQuestion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestion2ActionPerformed(evt);
            }
        });

        lblQuestion3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuestion3.setForeground(new java.awt.Color(204, 0, 204));
        lblQuestion3.setText("3. What is your Country ?");

        txtQuestion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestion3ActionPerformed(evt);
            }
        });

        lblQuestion4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuestion4.setForeground(new java.awt.Color(255, 51, 51));
        lblQuestion4.setText("4. How many feet do you have ?");

        txtQuestion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestion4ActionPerformed(evt);
            }
        });

        lblQuestion5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblQuestion5.setForeground(new java.awt.Color(255, 51, 51));
        lblQuestion5.setText("5. Are cats cute ?");

        txtQuestion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuestion5ActionPerformed(evt);
            }
        });

        lblMarks.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        btnCheck.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(51, 102, 255));
        btnCheck.setText("check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        lblAnswer1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblAnswer2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblAnswer3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblAnswer4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblAnswer5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        lblRed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRed.setText("A.red");

        lblYellow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYellow.setText("B.yellow");

        lblBlue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlue.setText("C.blue");

        lbl232.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl232.setText("A.232");

        lbl246.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl246.setText("B.246");

        lbl3333.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl3333.setText("C.3333");

        lblChina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChina.setText("A.China");

        lblRussia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRussia.setText("B.Russia");

        lblCanada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCanada.setText("C.Canada");

        lbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl2.setText("A.2");

        lbl3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl3.setText("B.3");

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl1.setText("c.1");

        lblNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNo.setText("B.No");

        lblYes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYes.setText("A.Yes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAnswer1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnswer2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuestion2)
                            .addComponent(lblQuestion4)
                            .addComponent(lblQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRed)
                            .addComponent(lblYellow)
                            .addComponent(lblBlue)
                            .addComponent(lbl232)
                            .addComponent(lbl246)
                            .addComponent(lbl3333)
                            .addComponent(lblCanada)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblRussia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblChina, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl2)
                            .addComponent(lbl3)
                            .addComponent(lbl1)
                            .addComponent(lblNo)
                            .addComponent(lblYes)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCheck)
                                .addGap(38, 38, 38)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblAnswer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtQuestion4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                .addComponent(txtQuestion3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtQuestion2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtQuestion1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtQuestion5))
                            .addComponent(lblAnswer5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeader)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion1)
                    .addComponent(txtQuestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblRed)
                .addGap(18, 18, 18)
                .addComponent(lblYellow)
                .addGap(18, 18, 18)
                .addComponent(lblBlue)
                .addGap(14, 14, 14)
                .addComponent(lblAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuestion2))
                .addGap(18, 18, 18)
                .addComponent(lbl232)
                .addGap(18, 18, 18)
                .addComponent(lbl246)
                .addGap(18, 18, 18)
                .addComponent(lbl3333)
                .addGap(16, 16, 16)
                .addComponent(lblAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuestion3)
                    .addComponent(txtQuestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblChina)
                .addGap(18, 18, 18)
                .addComponent(lblRussia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCanada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion4)
                    .addComponent(txtQuestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl2)
                .addGap(18, 18, 18)
                .addComponent(lbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblYes)
                                .addGap(31, 31, 31)
                                .addComponent(lblNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(lblAnswer5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnCheck)
                .addGap(59, 59, 59)
                .addComponent(lblMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        
        userAnswer = Integer.parseInt(txtQuestion1.getText());
        
        if (userAnswer == B)
        {
            lblAnswer1.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer1.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }    
        
        
        userAnswer = Integer.parseInt(txtQuestion2.getText());
        
        if (userAnswer == B)
        {
            lblAnswer2.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer2.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
        
        
        userAnswer = Integer.parseInt(txtQuestion3.getText());
        
        if (userAnswer == C)
        {
            lblAnswer3.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer3.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
        
        
        userAnswer = Integer.parseInt(txtQuestion4.getText());
        
        if (userAnswer == A)
        {
            lblAnswer4.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer4.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
        
        
        userAnswer = Integer.parseInt(txtQuestion5.getText());
        
        if (userAnswer == A)
        {
            lblAnswer5.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer5.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
        
        
        totalCorrect = 5 - Incorrect;
        totalIncorrect = 5 - Correct;
        
        lblMarks.setText(String.valueOf("The totalCorrect"));
        lblMarks.setText(String.valueOf(totalCorrect));
        lblMarks.setText(String.valueOf(""));
        lblMarks.setText(String.valueOf("The totalIncorrect"));
        lblMarks.setText(String.valueOf(totalIncorrect));
        
       
        
    }//GEN-LAST:event_btnCheckActionPerformed

    private void txtQuestion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestion3ActionPerformed
        
        userAnswer = Integer.parseInt(txtQuestion3.getText());
        
        if (C == userAnswer)
        {
            lblAnswer3.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer3.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
    }//GEN-LAST:event_txtQuestion3ActionPerformed

    private void txtQuestion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestion4ActionPerformed
        userAnswer = Integer.parseInt(txtQuestion4.getText());
        
        if (userAnswer == A)
        {
            lblAnswer4.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer4.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }

    }//GEN-LAST:event_txtQuestion4ActionPerformed

    private void txtQuestion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestion5ActionPerformed
         userAnswer = Integer.parseInt(txtQuestion5.getText());
        
        if (userAnswer == A)
        {
            lblAnswer5.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer5.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
    }//GEN-LAST:event_txtQuestion5ActionPerformed

    private void txtQuestion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestion2ActionPerformed
         userAnswer = Integer.parseInt(txtQuestion2.getText());
        
        if (userAnswer == B)
        {
            lblAnswer2.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer2.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
    }//GEN-LAST:event_txtQuestion2ActionPerformed

    private void txtQuestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuestion1ActionPerformed
         userAnswer = Integer.parseInt(txtQuestion1.getText());
        
        if (userAnswer == B)
        {
            lblAnswer1.setText(String.valueOf(True));
            Correct = Correct + 1;
        }
        else
        {
            lblAnswer1.setText(String.valueOf(False));
            Incorrect = Incorrect + 1;
        }
    }//GEN-LAST:event_txtQuestion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheMultipleChoiceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheMultipleChoiceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl232;
    private javax.swing.JLabel lbl246;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl3333;
    private javax.swing.JLabel lblAnswer1;
    private javax.swing.JLabel lblAnswer2;
    private javax.swing.JLabel lblAnswer3;
    private javax.swing.JLabel lblAnswer4;
    private javax.swing.JLabel lblAnswer5;
    private javax.swing.JLabel lblBlue;
    private javax.swing.JLabel lblCanada;
    private javax.swing.JLabel lblChina;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblMarks;
    private javax.swing.JLabel lblNo;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblQuestion3;
    private javax.swing.JLabel lblQuestion4;
    private javax.swing.JLabel lblQuestion5;
    private javax.swing.JLabel lblRed;
    private javax.swing.JLabel lblRussia;
    private javax.swing.JLabel lblYellow;
    private javax.swing.JLabel lblYes;
    private javax.swing.JTextField txtQuestion1;
    private javax.swing.JTextField txtQuestion2;
    private javax.swing.JTextField txtQuestion3;
    private javax.swing.JTextField txtQuestion4;
    private javax.swing.JTextField txtQuestion5;
    // End of variables declaration//GEN-END:variables
}
